web:
  build: .
  command: 'bash -c ''vendor/bin/heroku-php-apache2 public/'''
  working_dir: /app
  volumes:
    - '.:/app'
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
    - '443:443'
shell:
  command: bash
